name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md

env:
  DOCKER_REPOSITORY: abcfy2/muslcc-toolchain-ubuntu

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          short-description: ${{ github.event.repository.description }}
